FROM localhost/tomcat-s2i-builder:1.0
LABEL "io.openshift.s2i.build.commit.date"="Sun Mar 5 00:07:38 2023 -0300" \
      "io.openshift.s2i.build.commit.id"="17cc1fbe7bda1f842dd5a6f5863788f1d3cc4400" \
      "io.openshift.s2i.build.commit.ref"="main" \
      "io.openshift.s2i.build.commit.message"="Update README.md" \
      "io.openshift.s2i.build.source-location"="https://github.com/dandan2000/gs-rest-service.git" \
      "io.k8s.display-name"="gs-rest-service" \
      "io.openshift.s2i.build.image"="localhost/tomcat-s2i-builder" \
      "io.openshift.s2i.build.commit.author"="dandan2000 <daniel.celentano@gmail.com>"

USER root
# Copying in source code
COPY upload/src /opt/s2i/destination/src
# Change file ownership to the assemble user. Builder image must support chown command.
RUN chown -R 1001:0 /opt/s2i/destination/src
USER 1001
# Assemble script sourced from builder image based on user input or image metadata.
# If this file does not exist in the image, the build will fail.
RUN /usr/libexec/s2i/assemble
# Run script sourced from builder image based on user input or image metadata.
# If this file does not exist in the image, the build will fail.
CMD /usr/libexec/s2i/run
