apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: myapache
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: run1-myapache
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/instance: run1
        app.kubernetes.io/name: myapache
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/instance: run1
          app.kubernetes.io/name: myapache
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/danicele/apache-child:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8443
              scheme: HTTPS
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: myapache
          ports:
          - containerPort: 8443
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8443
              scheme: HTTPS
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: Service
  metadata:
    name: run1-myapache
  spec:
    internalTrafficPolicy: Cluster
    ports:
    - name: https
      port: "${{SERVICE_PORT}}"
    selector:
      app.kubernetes.io/instance: run1
      app.kubernetes.io/name: myapache
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: run1-myapache
  spec:
    host: run1-myapache.apps.kali.rlab.sh
    port:
      targetPort: https
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: passthrough
    to:
      kind: Service
      name: run1-myapache
      weight: 100
    wildcardPolicy: None
parameters:
- description: Any name can be possible
  displayName: Also here I can use the name I like
  name: SERVICE_PORT
  required: true
  value: "8443"