apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-app
spec:
  destination:
    namespace: user1-bgd
    server: https://kubernetes.default.svc
  project: demo-tasa
  source:
    path: Openshift/GitOps/bgd
    repoURL: 'https://github.com/dandan2000/practicasOCP.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
