apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: gs-rest-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gs-rest-service
  minReplicas: {{ .Values.hpa.replicas.min }}
  maxReplicas: {{ .Values.hpa.replicas.max }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
