kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: gs-rest-service
  labels:
    app: gs-rest-service
    app.kubernetes.io/component: gs-rest-service
    app.kubernetes.io/instance: gs-rest-service
spec:
  to:
    kind: Service
    name: gs-rest-service
    weight: 100
  port:
    targetPort: 8080-tcp
{{- if .Values.route.tls }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
