apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gs-rest-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gs-rest-service
  minReplicas: 15
  maxReplicas: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
