apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapache.fullname" . }}
  labels:
    {{- include "myapache.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "myapache.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      labels:
        {{- include "myapache.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8443
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /
              port: 8443
              scheme: HTTPS
#          resources:
#            {{- toYaml .Values.resources | nindent 12 }}
