kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: run1-myapache
spec:
  host: run1-myapache.apps.kali.rlab.sh
  to:
    kind: Service
    name: run1-myapache
    weight: 100
  port:
    targetPort: https
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None